import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-slate-500 shadow-md">
          <nav className="flex container mx-auto items-center justify-between p-4 text-white">
            <h1 className="text-2xl">Lexicon Library</h1>
            <div className="flex gap-4">Here you can put your links</div>
          </nav>
        </header>
        <main className="flex container mx-auto flex-col items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
